export enum ExpenseAction {
    CREATE = 'CREATE',
    SALE_ADMIN_REVIEW = 'SALE_ADMIN_REVIEW',
    SALE_ADMIN_REJECT = 'SALE_ADMIN_REJECT',
    APPROVE = 'APPROVE',
    REJECT = 'REJECT',
    /** Chủ đề xuất tự rút đơn khi chưa được duyệt. */
    WITHDRAW = 'WITHDRAW',
    CREATE_PAYMENT_ORDER = 'CREATE_PAYMENT_ORDER',
    CONFIRM_CASH_RELEASED = 'CONFIRM_CASH_RELEASED',
    CONFIRM_CASH_RECEIVED = 'CONFIRM_CASH_RECEIVED',
    CONFIRM_SPENT = 'CONFIRM_SPENT',
    CONFIRM_NOT_SPENT = 'CONFIRM_NOT_SPENT',
    CONFIRM_FUND_RETURNED = 'CONFIRM_FUND_RETURNED',
}
